### ISSUE TITLE
Ensure testng `@Test` attributes that are not migratable remain after migration

### ISSUE THREAD

**Issue by Philzen** [Philzen/rewrite-TestNG-to-JUnit5#4]
In the spirit of the ["Do no harm"-rule](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#do-no-harm) the TestNG annotation should remain after the migration if it contains an attribute that we don't have a migration for.

This way we ensure that the test suite behavior is not changed unintentionally and bring it to the attention of the recipe's user, so they can make their own choice whether to implement or change the behavior in JUnit 5.

```java
import org.testng.annotations.Test;
// …
@Test(description = "Foo!", retryAnalyzer = FooBarRetryAnalyzer.class)
```

should be migrated to

```java
import org.junit.jupiter.api.Test;
// …
@org.testng.annotations.Test(retryAnalyzer = FooBarRetryAnalyzer.class)
@Test
@DisplayName("Foo!")
```

**Comment by Philzen** [comment]
@timtebeek @mboegers i pretty much have this implemented in the feature branch,, but would like your feedback on this. Do you think this is an acceptable interpretation of the "Do no harm" rule? 

The challenge is that with this kind of migration converting a whole project, it's basically all-or-nothing, following the maxim

> If your recipe cannot determine that a change is safe, it should make no changes rather than making a potentially wrong change.

is hardly possible (would mean to roll back every change on every file once a single non-migratable annotation attribute is discovered). This take is to migrate as completely as possible (including [changing dependencies](https://github.com/Philzen/rewrite-TestNG-to-JUnit5/issues/29)) but leave these remainders behind which are conflict / road-bumps / showstoppers that user will have to resolve themselves.

**Comment by MBoegers** [comment]
@Philzen interesting question. In my implementation, I removed parameters with every step and at the end replaced the empty `@Test`. But as you point out, there are some points missing. 
Especially the not migratable retry is something that may _breaks_ the tests' semantics. That's bad.. Solutions I came up with, but have no favorite yet. 

1. Maybe commenting it, adding a TODO remark and mentioning this case in the description could be a first solution. This changes the semantics but denotes it, doesn't break the build in general and could be fixed by hand. 

2. Another solution could be adding another dependency and reimplement the retry in this way. Perhaps JUnit Pioneer has something. To make this obvious, you could fail the migration with a pointer to the `implement_retry_with_XY` recipe.

3. A third solution that came to me at breakfast is inspired by a claim of my database Professor: "[in informatics] ignoring a conflict and proceed is always an option". In this situation, we could interpret the following. Let the `@org.testng.annotations.Test(retryAnalyzer = FooBarRetryAnalyzer.class)` exist, remove the TestNG dependency and rely on the build failure. Yes, that would break the build, but it is the easiest solution, and it makes the change in semantics visible, as it has to be solved by hand.

**Comment by timtebeek** [comment]
Hi both; great to see you're working through this in such detail. From the options listed above I'd prefer option 3. For one-off migrations like this one I think that's acceptable to get folks most of the way there; and failing clearly on elements that can not be migrated automatically. I'd hope such cases are relatively rare, and tolerable for end users seeing that they only have to dive in where choices have to be made in the migration.

Commenting out the offending element (option 1) _could_ work, if we judge it unlikely that the retry failure needs to be retained. Ideally though I think that choice is best left up to the user, and hiding the element in a comment might mean it's missed in review leading to behavioral changes.

Option 2 would be a little out of scope I guess; again a choice that the user might want to make themselves, unless there's a very clear one to one option.

**Comment by Philzen** [comment]
Excellent, option 3. is also my fav and in my current implementation the least complex to implement. Many thanks for your valuable feedback :heart: 

@MBoegers this issue's scope is exclusively on how to generally handle non-migratable attributes (which i'm afraid a good handful of them will never have a good rewrite approach). For brainstorming ideas on how to shrink that gap there i have created  a separate issue which tracks those: https://github.com/Philzen/rewrite-TestNG-to-JUnit5/issues/5

**Comment by juherr** [comment]
Hi,

I see an option 4:
1. Keep testng tests that cannot be migrated
2. Mark them (comment, tag, ...) 
3. Integrate junit/testng-engine which is the best way to run test suites with both junit and testng tests

The test suite will compile and be runnable with the exact same behavior.

**Comment by Philzen** [comment]
> I see an option 4:

That's a good option to bring to the table. Implementation may be slightly more complex as it would 

1. require to add some precondition to 
   ```yaml
     - org.openrewrite.java.dependencies.RemoveDependency: 
         groupId: org.junit.support 
         artifactId: testng-engine 
   ``` 
   See https://github.com/Philzen/rewrite-TestNG-to-JUnit5/issues/29
2. also add a recipe to the list that adds testng-engine to projects that don't use it yet, using the same precondition
3. require to also generate a comment which states the particular attribute(s) that caused the annotation not to be migrated

My current tendency is therefore to proceed with option 3. – but your idea made me realize i should also generate a comment alongside the (non-compiling) remainder, helping users to understand that it was left there on purpose and advising on their options to mitigate it.

We should keep this option on the table once this project is mature enough to make it's way into the official OpenRewrite repository.

Good thinking, thanks!
